a13-5.10.223-2024-11_r6

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -56,6 +56,10 @@ jobs:
     - name: susfs_integration
       working-directory: ${{ env.KERNEL }}
       run: |
+        echo "[ check susfs driver ]"
+
+        grep -rn "susfs" ./common/drivers/kernelsu/Kconfig 2>/dev/null | head -5 || echo "not found"
+        
         git clone -b gki-android13-5.10 --single-branch https://gitlab.com/simonpunk/susfs4ksu.git
         
         cd ./susfs4ksu
@@ -101,7 +105,7 @@ jobs:
       working-directory: ${{ env.KERNEL }}
       run: |
         # export symbols
-        printf '\nEXPORT_SYMBOL(susfs_is_current_ksu_domain);\nEXPORT_SYMBOL(susfs_is_current_zygote_domain);\nEXPORT_SYMBOL(susfs_is_current_init_domain);\nEXPORT_SYMBOL(ksu_selinux_hide_running);\nEXPORT_SYMBOL(fake_state);\n' >> ./common/drivers/kernelsu/selinux/selinux.c
+        #printf '\nEXPORT_SYMBOL(susfs_is_current_ksu_domain);\nEXPORT_SYMBOL(susfs_is_current_zygote_domain);\nEXPORT_SYMBOL(susfs_is_current_init_domain);\nEXPORT_SYMBOL(ksu_selinux_hide_running);\nEXPORT_SYMBOL(fake_state);\n' >> ./common/drivers/kernelsu/selinux/selinux.c
         
     - name: configure_build_cmds
       run: |
